<a href="https://colab.research.google.com/github/alexandrufalk/tensorflow/blob/Master/Session1_AI_convention_workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Applying pretrained LLMs on NLP tasks

> **⚠️ Disclaimer:** *Using LLMs is subject to approvals.*

In [1]:
# Setup environment for this notebook

%pip install datasets pandas numpy scikit-learn torch transformers trl

Collecting datasets
  Downloading datasets-3.1.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.5.0+cu121)
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Collecting trl
  Downloading trl-0.12.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.6)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.26.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.10/dist-packages (from torch) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: accelerate>=0.34.0 in /usr/local/lib/python3.10/dist-packages (from trl) (1.1.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from trl) (13.9.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.34.0->trl) (5.9.5)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.17.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->trl) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->trl) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->trl) (0.1.2)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
Downloading datasets-3.1.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 4.3 MB/s eta 0:00:00
Downloading trl-0.12.0-py3-none-any.whl (310 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.2/310.2 kB 7.9 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 3.7 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 10.3 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 4.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 6.3 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets, trl
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.1.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 trl-0.12.0 xxhash-3.5.0

## What is generative AI?
Generative AI(Gen AI) is a subset of artificial intelligence(AI) that uses generative models to produce new text, images, videos and other forms of data. These networks are adept at identifying patterns within the training data, which allows them to produce new, similar data points that maintain the statistical properties of the original dataset. Gen AI is widely used in industry such as for creating realistic CGI and virtual environments in entertainment and movie productions. The healthcare sector leverages generative AI for drug discovery and enhancing medical imaging. In finance, it’s used for simulating market scenarios and generating synthetic data for stress testing etc

## What is a Large Language Model(LLM)?
LLMs are a category of foundation models characterized by their extensive parameter count, often reaching into the billions. These models undergo pretraining on vast datasets, which equips them with the ability to comprehend and produce natural language, as well as other forms of content. LLMs excel in tasks involving language understanding and generation, making them a powerful tool in various applications. Their capacity to learn from massive amounts of data allows them to generate human-like text and perform complex language-related tasks with high proficiency.

## Popular LLMs released recently:
- #### GPT-4o, GPT-4o mini by OpenAI
- #### LLama 3.2 by Meta
- #### Gemma by Google
- #### Models by Mistral
- #### Phi 3.5 mini by Microsoft

## How to apply LLMs for enterprise applications?

<center><img src="work/session_1/howtobuildllmapp.jpg" width="800" height="500"></center>

## Hugging Face
#### Website: https://huggingface.co/
<br>

**Hugging Face** is a collaborative platform to create, train and deploy machine learning and neural network models using open source code.<br>
<center><img src="work/session_1/hf.jpg" width="700" height="300"></center> <br>

### Architecture of LLMs: Introductory concepts

**Transformer**: <br> Transformer is a deep learning model and the foundational block of LLMs such as BERT and GPT. It is a sequence-to-sequence architecture based model that uses _**attention**_ mechanism to capture context information in the input sequence. Some significant components in the transformer are:
* **Tokenization and Input embeddings**: Tokenization is the process of converting a sequence of text into smaller unit suchs as words or subwords. The input sequence to the transformer is tokenized and mapped to a high-dimensional vector space to obtain input embeddings.
* **Encoder**: The encoder processes the input embeddings, incorporating positional encodings to maintain the order of tokens. It computes attention weights to determine the significance of each token relative to others, generating a hidden state that encapsulates contextual information.
* **Decoder**: This hidden state information is passed to decoder block to generate the target output. The decoder predicts probabilities over different words to predict a output sequence that is coherent to the learned context.

<center><img src="work/session_1/transformerjayalm.jpg" width="800" height="500"></center>

**Hugging Face** provides some core services like: <br>
#### 1. Transformers Library
Transformers provides **APIs and tools** to easily download and train state-of-the-art pretrained models. These models support common tasks in different modalities, such as: <br>
- *Natural Language Processing*: text classification, named entity recognition, question answering, language modeling, summarization, translation, multiple choice, and text generation. <br>
- *Computer Vision*: image classification, object detection, and segmentation <br>
- *Audio*: automatic speech recognition and audio classification. <br>

#### 2. Model Hub
The Model Hub is where models are hosted for storage, discovery, and sharing. <br>
**Link: https://huggingface.co/models**

#### 3. Datasets
Training a LLM may need multi-gigabyte datasets, especially if you’re planning to pretrain a model from scratch. In these cases, even loading the data can be a challenge! Hugging Face datasets library allows to load a dataset in a single line of code and process large datasets without any memory constraints for optimal speed and efficiency. Hugging Face also provides a vast repository of NLP datasets that support the training and benchmarking of ML models.

## Example 1: Apply pretrained LLMs on NLP tasks using Hugging Face Transformers : Pipelines

Hugging Face Transformers **Pipelines** are objects that abstract most of the complex code from the Transformers library, offering a simple API dedicated to tasks. The list of currently accepted tasks are : https://huggingface.co/docs/transformers/v4.46.2/en/main_classes/pipelines#transformers.pipeline.task

<center><img src="work/session_1/hfnlp_pipeline.jpg" width="700" height="300"></center>

In [2]:
# Import libraries
import os
import pandas as pd
from transformers import pipeline

# Setup parameters for jupyter notebook
import warnings
pd.set_option('max_colwidth', None)
warnings.filterwarnings('ignore')

# Setup certificate permissions to access external API from Continental's VPN
os.environ['REQUESTS_CA_BUNDLE']  = "work/certificates.pem"

In [ ]:
# Example: Text classification for sentiment analysis
# Apply LLM to determine the emotional tone, sentiment or attitude expressed in a text.
# Sentiments used for this example are positive and negative

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english",
    trust_remote_code=True
)

data = [
    "Sunrise is a beautiful time of the day",
    "Cloudy days can be gloomy and reduce productivity."
]

print(sentiment_pipeline(data))

In [ ]:
# Example: Knowledge distillation for question answering
# Apply LLM to comprehend a given context and generate precise answers to questions related to that context.
# The process involves understanding the question, identifying relevant information within the context, and
# formulating an accurate response.

oracle = pipeline(
    model="distilbert/distilbert-base-cased-distilled-squad"
)

print(oracle(question="Where do I live?", context="My name is Wolfgang and I live in Berlin"))

{'score': 0.9925103187561035, 'start': 34, 'end': 40, 'answer': 'Berlin'}

In [ ]:
# Example: Knowledge distillation for summarization of text
# Apply LLM to generate concise summaries of given text samples. This involves analyzing the input text,
# identifying key points and main ideas, and producing a coherent summary that captures the essence of
# the original content.

text_to_summarize = "Advantages of AI: AI drives down the time taken to perform a task. It enables multi-tasking \
and eases the workload for existing resources. AI enables the execution of hitherto complex tasks without significant \
cost outlays. AI operates 24x7 without interruption or breaks and has no downtime. AI augments the capabilities of \
differently abled individuals. AI has mass market potential, it can be deployed across industries."

summarizer = pipeline(
    "summarization",
    model="google/flan-t5-small"
)

print(summarizer(text_to_summarize, min_length=5, max_length=20))

[{'summary_text': 'AI enables multi-tasking and eases the workload.'}]

In [ ]:
# Example: Zero shot classification
# Apply LLM to for zero-shot text classification, categorizing sample text into predefined categories
# without the need for training examples. LLMs leverage their pre-trained knowledge to understand the
# text and assign it to the most appropriate category. This method is suitable when labeled data is scarce or unavailable

classifier = pipeline(
    "zero-shot-classification",
    model="distilbert/distilbert-base-uncased-finetuned-sst-2-english"
)

classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

Failed to determine 'entailment' label id from the label2id mapping in the model config. Setting to -1. Define a descriptive label2id mapping in the model config to ensure correct outputs.

{'sequence': 'This is a course about the Transformers library',
 'labels': ['education', 'business', 'politics'],
 'scores': [0.40379297733306885, 0.3503463566303253, 0.24586066603660583]}

In [ ]:
# Pipeline batching
# Apply a task pipeline on a dataset

from datasets import load_dataset
from transformers.pipelines.pt_utils import KeyDataset
from tqdm.auto import tqdm

dataset = load_dataset("stanfordnlp/imdb")

summarizer = pipeline(
    "summarization",
    model="google/flan-t5-small",
    truncation=True
)

# Apply declared pipeline on a small slice of loaded dataset for demonstration purposes
for out in tqdm(summarizer(KeyDataset(dataset["unsupervised"], "text")[:10], max_length=50)):
    print(out)

Generating train split: 100%|██████████| 25000/25000 [00:00<00:00, 138136.11 examples/s]
Generating test split: 100%|██████████| 25000/25000 [00:00<00:00, 148200.24 examples/s]
Generating unsupervised split: 100%|██████████| 50000/50000 [00:00<00:00, 145268.45 examples/s]
100%|██████████| 10/10 [00:00<00:00, 45540.76it/s]

{'summary_text': 'This is just a precious little diamond. The play, the script are excellent. I can\'t compare this movie with anything else, maybe except the movie "Leon" wonderfully played by Jean Reno and Natalie Portman. But...'}
{'summary_text': "Luc Besson's sexy thriller is one of my favourite films of all time. It is a brilliantly acted film, and I can't wait to see it again."}
{'summary_text': 'The Nikita is based on the same name as Roy Dupuis and Pet Wilson. It is a true story about a young man who is in love with a woman who has a crush on him. The movie'}
{'summary_text': "I'm not a fan of Japanese films, but this movie is a good one. It's a great movie, but it's not worth watching."}
{'summary_text': "I'm not a fan of Nikita, but I've seen it a few times. It's a good movie, but it's not worth watching."}
{'summary_text': 'summary: Stylish thriller? Hardly! This French action film from director Luc Besson is more confused and unsure about itself than anything else. I have seen recently...'}
{'summary_text': "Luc Besson's film with Anne Parillaud, Tchéky Karyo and Jean Reno is a master. The photography by Thierry Arbogast was perfect, especially the blue lighting at the pharmacy"}
{'summary_text': "This is a great movie. It's a good movie, but it's not a bad movie. The acting is excellent. The plot is believable and the acting is great. I'm a fan of the"}
{'summary_text': 'Luc Besson\'s "La Femme Nikita" is one of the best films of the 1990s. It\'s a great film with a very good cast and a good cast.'}
{'summary_text': 'Luc Besson\'s latest film, "La Femme Nikita," is a sexy and violent action film he\'s been working on for a decade.'}

## Example 2: Finetuning a LLM model

#### Challenges in using off-the-shelf pretrained models

Applying existing pretrained models to specific problem domains may produce generic or less accurate outputs. This can be corrected by following alternatives:
1. **Training your own pretrained model on your own domain data** <br>
    - General challenges in pretraining are: *Data, Technical expertise, Ethical concerns, Computational cost etc*
    <br><br>
2. **Finetune pretrained model on your domain data**

<img src="work/session_1/finetuning_process_02.jpg" width="700" height="300">|<img src="work/session_1/chart_e2.jpg" width="700" height="300">

### **Finetuning GPT-2 model with Hugging Face**

GPT-2 is an open source "decoder-only" **causal language model** designed to generate new pieces of text.

In [ ]:
import time
from datasets import load_dataset
import torch
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import TrainingArguments, Trainer
from trl import SFTTrainer

In [ ]:
# Define base model that will be finetuned to custom dataset

model_id = "openai-community/gpt2"

tokenizer = AutoTokenizer.from_pretrained(model_id)
pretrained_model = AutoModelForCausalLM.from_pretrained(model_id)

In [ ]:
# The output from the pretrained model prior to fine-tuning for the task: text completion
# LLM is provided with an initial text prompt, and the model then attempts to complete the text in a coherent
# and contextually appropriate way

text = "Quote: Imagination is more"
inputs = tokenizer(text, return_tensors="pt")

outputs = pretrained_model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Quote: Imagination is more than just a tool for the mind. It's a tool for the body.

I'm not saying that you can't use it to create a beautiful, beautiful world. But it's a

In [ ]:
# Load dataset from the Hugging Face Hub for finetuning the model
dataset = load_dataset("Abirate/english_quotes")

# View sample rows from dataset
pd.DataFrame.from_dict(dataset["train"]).iloc[:5,:2]

Generating train split: 100%|██████████| 2508/2508 [00:00<00:00, 330162.72 examples/s]

,quote,author
0,“Be yourself; everyone else is already taken.”,Oscar Wilde
1,"“I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.”",Marilyn Monroe
2,“Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”,Albert Einstein
3,"“So many books, so little time.”",Frank Zappa
4,“A room without books is like a body without a soul.”,Marcus Tullius Cicero

In [ ]:
# Define how we'd like our outputs to look like after fine-tuning.

def formatting_func(example):
    text = f"Quote: {example['quote'][0]}\nAuthor: {example['author'][0]}<eos>"
    return [text]

In [ ]:
# Fine-tune the model

MAX_STEPS = 10

training_args = transformers.TrainingArguments(
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=2,
    max_steps=MAX_STEPS,
    learning_rate=2e-4,
    logging_steps=1,
    output_dir="outputs",
)

trainer = SFTTrainer(
    model=pretrained_model,
    train_dataset=dataset["train"],
    args=training_args,
    formatting_func=formatting_func,
)

trainer.train()

Map: 100%|██████████| 2508/2508 [00:00<00:00, 127301.62 examples/s]
max_steps is given, it will override any value given in num_train_epochs

TrainOutput(global_step=10, training_loss=1.2814641892910004, metrics={'train_runtime': 37.0933, 'train_samples_per_second': 1.078, 'train_steps_per_second': 0.27, 'total_flos': 297015552000.0, 'train_loss': 1.2814641892910004, 'epoch': 6.666666666666667})

In [ ]:
# Ask the model for text completion after fine-tuning.
# Mind that now the model nicely adheres to the desired output format.

text = "Quote: Imagination is more"
inputs = tokenizer(text, return_tensors="pt")

finetuned_model = AutoModelForCausalLM.from_pretrained(f"outputs/checkpoint-{MAX_STEPS}")
outputs = finetuned_model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

Setting `pad_token_id` to `eos_token_id`:None for open-end generation.

Quote: Imagination is more than just a feeling. It's also a powerful tool.
Author: Oscar Wilde<eos>ungjin<eos>ang>raeos>brink<eos>ung

### References

https://huggingface.co/ <br>
https://huggingface.co/docs/transformers/index <br>
https://huggingface.co/docs/transformers/main_classes/pipelines <br>
https://nurdle.ai/selecting-hugging-face-models-5-step-guide <br>
https://jalammar.github.io/illustrated-transformer/ <br>
https://proceedings.neurips.cc/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf <br>
https://magazine.sebastianraschka.com/p/finetuning-llms-with-adapters <br>
https://www.nvidia.com/en-us/glossary/generative-ai/ <br>

### Conclusion

**In this session we learnt**:
* Introductory concepts: Generative AI, Large Language Models(LLM), Transformer model and included process such as word embeddings, tokenization, encoder, decoder
* Applying pretrained models using Hugging Face Pipelines
* Finetuning a pretrained generative model with our own dataset